# Generated by Django 5.0.6 on 2024-06-15 21:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_alter_room_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_guid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
