# Generated by Django 5.0.6 on 2024-06-15 21:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0004_meeting_meeting_guid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="meeting_guid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
