# Generated by Django 5.0.6 on 2024-06-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0008_meeting_meeting_guid_room_room_guid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="room",
        ),
    ]
